### ISSUE TITLE
Error: Invalid Syntax

### ISSUE THREAD

**Issue by darkdemon28** [shubhamnagota/WeLeakInfoScrapper#1]
When running:

python app.py

The following error occurs:
 File "app.py", line 40
    print(f"\nSearch Term : {searchTerm} ---> Type : {searchType}")
                                                                 ^
SyntaxError: invalid syntax

**Comment by shubhamnagota** [comment]
Hi @darkdemon28
Can you please tell your python version.

There might be issue with that. I created it using Python3.x
Try with that.

**Comment by darkdemon28** [comment]
Just to give a bit of context here, I'm using Windows 10 Pro and the output I get from the following commands:

python --version: 2.7.17
py --version: 3.8.0

When I run 'python app.py' I get the syntax error, however when I run 'py app.py' I get this error:

Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from openpyxl import Workbook
ModuleNotFoundError: No module named 'openpyxl'

I did the 'pip install -r requirements.txt' and it says 'Requirement already satisfied: openpxy1==2.6.2'

**Comment by darkdemon28** [comment]
Ok so I uninstalled version 2.7 of python as that and python3 seemed to be clashing when trying to run that app.py but it does nothing when I run it, possibly because it is no longer https://search.weleak.info/ it is now https://weleakinfo.com/search

**Comment by darkdemon28** [comment]
Now I'm getting this output:

DevTools listening on ws://127.0.0.1:52617/devtools/browser/8e9061c0-4057-4b85-b4d0-408caa6be25d
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    driver = webdriver.Remote(
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.18362 x86_64)

**Comment by darkdemon28** [comment]
Oh also the version of Chrome has now changed to version: 78.0.3904.108 and there is no way of rolling back so I've got a feeling there are a few things that need to be adjusted before this will work which is a damn shame really as I was hoping to use this to go through a list of my family's email addresses and generate the output file that I would turn into a CSV for use with my web app I'm building in NodeJS / ExpressJS.

**Comment by darkdemon28** [comment]
Why has this been closed? The issue has not been solved!!
